#!/bin/bash
# This hook is sourced after every virtualenv is activated.

export PROJECT_NAME=$(basename $VIRTUAL_ENV)
if [[ -d $HOME/projects/$PROJECT_NAME ]]; then
    export PROJECT_DIR=$HOME/projects/$PROJECT_NAME
    cd $PROJECT_DIR
fi
